swift-server/swift-aws-lambda-events

Examples/Simple/Package.swift, Examples/Simple/Sources/APIGateway/APIGatewayProxyLambda.swift, Sources/AWSLambdaEvents/ALB.swift, Sources/AWSLambdaEvents/APIGateway+V2.swift, Sources/AWSLambdaEvents/APIGateway.swift, Sources/AWSLambdaEvents/AppSync.swift, Sources/AWSLambdaEvents/Cloudwatch.swift, Sources/AWSLambdaEvents/DynamoDB.swift, Sources/AWSLambdaEvents/S3.swift, Sources/AWSLambdaEvents/SES.swift, Sources/AWSLambdaEvents/SNS.swift, Sources/AWSLambdaEvents/SQS.swift, Tests/AWSLambdaEventsTests/ALBTests.swift, Tests/AWSLambdaEventsTests/APIGateway+V2Tests.swift, Tests/AWSLambdaEventsTests/APIGatewayTests.swift, Tests/AWSLambdaEventsTests/AppSyncTests.swift, Tests/AWSLambdaEventsTests/CloudwatchTests.swift, Tests/AWSLambdaEventsTests/DynamoDBTests.swift, Tests/AWSLambdaEventsTests/S3Tests.swift, Tests/AWSLambdaEventsTests/SESTests.swift, Tests/AWSLambdaEventsTests/SNSTests.swift, Tests/AWSLambdaEventsTests/SQSTests.swift
We have potential name clashes with existing AWS libraries, if we namespace our events under the service name. For example `S3.Event`. This problem has been documented here: https://github.com/swift-server/swift-aws-lambda-runtime/issues/119
This PR picks up the fix, that was initially intended to land in the runtime repo directly: https://github.com/swift-server/swift-aws-lambda-runtime/pull/203
No more namespace issues with AWS libraries.
=> Fix event namespacing problems

docker/docker-compose.al2.55.yaml
motivation: 5.5 release is available
changes: update docker CI setup to use the release version of 5.5
=> Use release version of 5.5 in CI

Sources/AWSLambdaEvents/APIGateway+V2.swift
Make APIGatewayV2Request authorizer claims optional.
The current non-optional claims property is not compatible with the Lambda Runtime Interface Emulator.
Aside from this, the AWS Docs specify a `null` value in this example: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format
Make APIGatewayV2Request authorizer claims optional.
APIGatewayV2Request authorizer claims is optional, allowing a nil value so that the Lambda Runtime Interface Emulator works with this library and so it's in accordance with the AWS docs.
=> Make APIGatewayV2Request authorizer claims optional

Sources/AWSLambdaEvents/SES.swift
Make commonHeaders.messageId optional
Sometimes the SES event does not provide a messageId in the commonHeaders section
SES events without a messageId in commonHeaders decode
=> SES messageId event fix

Sources/AWSLambdaEvents/ALB.swift, Sources/AWSLambdaEvents/APIGateway+V2.swift, Sources/AWSLambdaEvents/APIGateway.swift, Sources/AWSLambdaEvents/AWSRegion.swift, Sources/AWSLambdaEvents/AppSync.swift, Sources/AWSLambdaEvents/Cloudwatch.swift, Sources/AWSLambdaEvents/DynamoDB.swift, Sources/AWSLambdaEvents/S3.swift, Sources/AWSLambdaEvents/SES.swift, Sources/AWSLambdaEvents/SNS.swift, Sources/AWSLambdaEvents/SQS.swift, Sources/AWSLambdaEvents/Utils/DateWrappers.swift, Sources/AWSLambdaEvents/Utils/HTTP.swift, scripts/soundness.sh
This is an alternative to: #13. The main difference is that we don't introduce new `Protocols`, which only inherit from `Decodable` and `Sendable`. For this reason adopters don't need to learn about our helper protocols. Let me know what you think.
As a side note: I still really dislike the Date propertyWrappers and I still consider them an anti-pattern, which only purpose is to work around Codable limitations.
=> Add Sendable support

Sources/AWSLambdaEvents/FunctionURL.swift, Tests/AWSLambdaEventsTests/FunctionURLTests.swift
Add request and response object models for [invoking Lambda function URLs](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html).
Instead of having to spin up (and pay for) API Gateway endpoints, Lambdas can spin up bare URLs for public access.
There are no existing request or response objects for these requests like there are for other event types.
- Created a `FunctionURLRequest` object matching [the request payload format](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-request-payload)
- Created a `FunctionURLResponse` object matching [the response payload format](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-response-payload)
These payloads are very similar (but not identical to) API Gateway V1 requests, so this is mostly …
=> Add support for bare Lambda function URLs

Sources/AWSLambdaEvents/SNS.swift, Tests/AWSLambdaEventsTests/SNSTests.swift
Updated incorrect sns event fields to match correct format
Issue: #25 
Updated incorrect sns event fields to match correct format. [Correct format can be seen here](https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html)
Correct parsing of a SNS Event
=> Updated incorrect sns event fields to match correct format

Sources/AWSLambdaEvents/Cognito.swift, Sources/AWSLambdaEvents/Docs.docc/index.md, Tests/AWSLambdaEventsTests/CognitoTests.swift, readme.md
Support for one Cognito Lambda Trigger (`PreSignUp_SignUp`), with infrastructure to support all 20 others.
I've been playing around with implementing WebAuthn (passkeys) using only Swift. It turned out to be complex, because Cognito doesn't support it yet, and requires the use of 3/4 lambda triggers.
Added a basic Cognito trigger enum that should be able to model all 21 lambda trigger types. Made some tests for the single trigger I've currently actually used.
Cognito triggers are a little funny in that they all have a common shape, but differ in some ways depending on the type. And, because there are so many (21 as of right now), I didn't want to create a bunch of duplicate structs. So, I opted for a enum that stores the trigger-specific data.
I think this change is potentially useful, …
=> Initial cognito trigger support

Sources/AWSLambdaEvents/AWSRegion.swift
Added the Amazon regions created until January 2023 that are not included in the `AWSRegion` type.
Although there is a way to work with non existing regions at `AWSRegion` class, It could be helpful add the new available Amazon regions to the mentioned class.
The regions added in this PR are listed below.
* **Africa**
* Cape City (`af-south-1`)
* **Asia Pacific**
* Melbourne (`ap-southeast-4`)  
* Hyderabad (`ap-south-2`)
* Yakarta (`ap-southeast-3`)
* **Europe**
* Milano, Italy (`eu-south-1`)
* Madrid🤘😜, Spain  (`eu-south-2`)
* Zurich, Switzerland (`eu-central-2`)
* **Middle East**
* UAE(`me-central-1`)  
This PR presents only modification in the `AWSRegion` class, specifically in the `all` static variable in order to add the new static variables created for each of the new regions
Those …
=> Added new available Amazon regions

Sources/AWSLambdaEvents/SNS.swift, Tests/AWSLambdaEventsTests/SNSTests.swift
Update `SNSEvent.Message` coding keys to match go models & documentation
When trying to decode an `SNSEvent` as the lambda's event (using runtime `1.0.0-alpha.1`), I am getting:
```
2023-05-18T14:51:32+0000 warning Lambda : lifecycleIteration=16 lambda handler returned an error: requestDecoding(Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "SigningCertURL", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "Records", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "Sns", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"SigningCertURL\", intValue: nil) (\"SigningCertURL\").", underlyingError: nil)))
```
It seems that the model's coding keys have changed with the proper …
=> Update SNSEvent.Message Coding Keys

Sources/AWSLambdaEvents/Utils/HTTP.swift, Tests/AWSLambdaEventsTests/Utils/HTTPHeadersTests.swift
Adds a new method `first(name:)` to `HTTPHeaders` (aka just `[String: String]`).
I first noticed absence of such a function when I was trying to get 2 different headers of a Github request.
Using capitalized header names as mentioned in Github docs, or lowercased names, both would fail.
(**EDIT:** To be clear, i think one header had a capitalized name and the other a lowercased name, which is just an inconsistency by Github in this case.)
That was when [I copy-pasted `swift-nio`'s `HTTPHeaders.first(name:)` function to the lambda target](https://github.com/vapor/penny-bot/commit/bf98089237fbbefe7c24b00802f98092a446a2b2), which fixed the issue.
I think this will be a generally useful function, as it's even available in NIO's implementation of `HTTPHeaders`.
Copy-paste [NIO's implementation …
=> add `HTTPHeaders.first(name:)`

Sources/AWSLambdaEvents/APIGateway+V2.swift, Tests/AWSLambdaEventsTests/APIGateway+V2IAMTests.swift, Tests/AWSLambdaEventsTests/APIGateway+V2Tests.swift, docker/docker-compose.al2.56.yaml, docker/docker-compose.al2.57.yaml, docker/docker-compose.al2.58.yaml, docker/docker-compose.al2.59.yaml, docker/docker-compose.al2.main.yaml
add support for `iam` authorizer in addition to JWT
See https://github.com/swift-server/swift-aws-lambda-events/issues/40
I need to deploy Swift Lambda function protected by IAM
- Add an optional `iam` element inside `requestContext` 
- mark `jwt` element as optional (this is a breaking change for existing application consuming this property) 
We can use API Gateway with IAM authentication.
Existing code using `jwt` authentication will need to handle the optional (but marking it as non optional was incorrect)
=> add support for IAM authorizers

Sources/AWSLambdaEvents/APIGateway+V2.swift, Sources/AWSLambdaEvents/APIGatewayLambdaAuthorizers.swift, Tests/AWSLambdaEventsTests/APIGatewayLambdaAuthorizerTest.swift
Add support for Lambda Authorizers as requested by issue https://github.com/swift-server/swift-aws-lambda-events/issues/39
Lambda authorizers are Lambda functions called by Amazon API Gateway to delegate authorization decisions. There are used both by the Rest API and the HTTP API gateway (aka APIGateway and APIGatewayv2) 
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html
This changes introduce three modifications.
The first modification allows Swift developer to write Lambda functions protected by a Lambda authorizer function.
1. support the `lambda` object under `authorizer` in `APIGatewayV2.swift`. This allows Lambda function behind a Lambda Authorizer to gather the identity and authorization data shared by the Lambda authorizer …
=> Add support for AWS Lambda Authorizers

Sources/AWSLambdaEvents/Cloudwatch.swift
Hi there,
I assume you meant EventBridgeEvent to be consumable by client libraries. This PR just changes the visibility of the typealias from internal to public.
=> Update EventBridgeEvent visibility

Sources/AWSLambdaEvents/APIGateway+V2.swift, Tests/AWSLambdaEventsTests/APIGateway+V2Tests.swift
Add mTLS client certificate information to `APIGatwayV2Request`
When configuring mTLS in API Gatway (HTTP v2), the event payload contains information about the client certificate. This information is currently not present in the `APIGatwayV2Request` structure.
Added optional fields for `authentication.clientCert` on `APIGatewayV2Request` according to the AWS "spec".
mTLS client certification information is decoded and passed to the lambda handler.
=> Add mTLS client certificate information to APIGatwayV2Request

Package.swift, Sources/AWSLambdaEvents/ALB.swift, Sources/AWSLambdaEvents/APIGateway+V2.swift, Sources/AWSLambdaEvents/APIGateway.swift, Sources/AWSLambdaEvents/APIGatewayLambdaAuthorizers.swift, Sources/AWSLambdaEvents/AppSync.swift, Sources/AWSLambdaEvents/FunctionURL.swift, Sources/AWSLambdaEvents/LambdaGatewayProxyEvent.swift, Sources/AWSLambdaEvents/Utils/HTTP.swift, Tests/AWSLambdaEventsTests/ALBTests.swift, Tests/AWSLambdaEventsTests/APIGateway+V2Tests.swift, Tests/AWSLambdaEventsTests/APIGatewayTests.swift, Tests/AWSLambdaEventsTests/FunctionURLTests.swift, Tests/AWSLambdaEventsTests/LambdaGatewayProxyEventTests.swift
Use Swift HTTP types package for status and method
As mentioned in #46 there is some overlap between the definitions of http types in this library and in the recent [Apple Swift HTTP Types library](https://github.com/apple/swift-http-types). 
This means when working with Swift HTTP Types, you have to convert from the AWS Lambda Events representation of http types into Swift HTTP Types. 
I have replaced the request method and response status Swift types in this library with those from Swift HTTP Types.
Now you must use Swift HTTP Types for request methods and response types.
I initially indented to also replace the representation of headers to Swift HTTP Types' HTTPField, but this turned out to be... non-trivial. The way AWS encodes the different forms of headers in different situations …
=> Use Swift HTTP types package for status and method

Sources/AWSLambdaEvents/ALB.swift, Sources/AWSLambdaEvents/APIGateway+V2.swift, Sources/AWSLambdaEvents/APIGateway.swift, Sources/AWSLambdaEvents/APIGatewayLambdaAuthorizers.swift, Sources/AWSLambdaEvents/AWSRegion.swift, Sources/AWSLambdaEvents/AppSync.swift, Sources/AWSLambdaEvents/CloudFormation.swift, Sources/AWSLambdaEvents/Cognito.swift, Sources/AWSLambdaEvents/DynamoDB.swift, Sources/AWSLambdaEvents/FunctionURL.swift, Sources/AWSLambdaEvents/LambdaGatewayProxyEvent.swift, Sources/AWSLambdaEvents/S3.swift, Sources/AWSLambdaEvents/SES.swift, Sources/AWSLambdaEvents/SNS.swift, Sources/AWSLambdaEvents/SQS.swift, Sources/AWSLambdaEvents/Utils/DateWrappers.swift
The code base uses pre compiler directives to selectively add `Sendable` protocol to `struct` when compiling on Swift >= 5.6
```
#if swift(>=5.6)
extension XXX: Sendable
#endif
```
This PR removes this old code and moves all `Sendable` definitions to the same line as the `struct` definition.
```
public struct XXX: Sendable
```
=> cleanup pre Swift 5.6 code

Sources/AWSLambdaEvents/BedrockAgent.swift, Tests/AWSLambdaEventsTests/BedrockAgentTests.swift
Add a struct to support the payload sent by Amazon Bedrock agents 
https://docs.aws.amazon.com/bedrock/latest/userguide/agents-lambda.html#agents-lambda-input
=> add support for BedrockAgents

Sources/AWSLambdaEvents/Cognito.swift, Tests/AWSLambdaEventsTests/CognitoTests.swift
Added Cognito events for PostConfirmation, PostAuthentication, CustomMessage and handled the other PreSignUp trigger sources: `PreSignUp_ExternalProvider` and `PreSignUp_AdminCreateUser`
Continuing the work done #27, I've added support for some more Cognito trigger events.
I'm not sure of the original author's intentions for how to handle triggers that are of the same "shape". E.g. there are three different trigger sources that follow the "PreSignUp" shape (`PreSignUp_SignUp`, `PreSignUp_ExternalProvider` and `PreSignUp_AdminCreateUser`). The original author had named a single enum case `.preSignUpSignUp`, but the other two trigger sources would have been exactly the same. 
I have therefore changed the name to `preSignUp` and implemented three new ones (PostConfirmation, …
=> Cognito Triggers - PreSignUp, PostConfirmation, PostAuthentication, CustomMessage

.github/workflows/pull_request.yml
Use GitHub actions for CI
- We like GitHub actions
- Add workflow
- We will be able to deprecate our existing CI
=> Use GitHub actions for CI

Sources/AWSLambdaEvents/ALB.swift, Sources/AWSLambdaEvents/APIGateway.swift, Sources/AWSLambdaEvents/Cloudwatch.swift, Sources/AWSLambdaEvents/DynamoDB.swift, Sources/AWSLambdaEvents/FunctionURL.swift, Sources/AWSLambdaEvents/S3.swift, Sources/AWSLambdaEvents/SES.swift, Sources/AWSLambdaEvents/SNS.swift, Sources/AWSLambdaEvents/Utils/DateWrappers.swift
In order to reduce binary size, we want to depend only on FoundationEssentials on Linux.
We should add CI in the future that checks, that we don't link full Foundation.
=> Use FoundationEssentials if possible

Sources/AWSLambdaEvents/Cognito.swift
Just a small change, the clientId is only sent if the request came from a client, not if e.g. you do it in the console or use AdminUpdateUserAttributes directly (not via an app client)
=> CognitoEvent CallerContext ClientId should be optional

Sources/AWSLambdaEvents/Cloudwatch.swift, Tests/AWSLambdaEventsTests/CloudwatchTests.swift
Add EventBridge S3Events notifications
I want to handle S3 event notifications sent via EventBridge with a Lambda. These events are not defined.
Based on [AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/EventBridge.html), I've added the following events:
- Object Created
- Object Deleted
- Object Restore Initiated
- Object Restore Completed
- Object Restore Expired
- Object Storage Class Changed
- Object Access Tier Changed
- Object ACL Updated
- Object Tags Added
- Object Tags Deleted
I've also added tests for S3 events with examples on S3 [EventBridge event message structure](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ev-events.html).
You can now handle S3 events notifications from EventBridge!
=> Add EventBridge S3Events notifications

.gitignore
.index-build is a temporary build directory created by the VSCode plugin for Swift
=> add .index-build to gitignore

Sources/AWSLambdaEvents/S3.swift
Make S3 Object eTag optional, because it's not always there.
I'm seeing real events without an eTag, which naturally is causing decoding failures.
Made S3 Object eTag optional.
S3 Object eTag is now optional...
=> Make S3 eTag optional

.devcontainer/devcontainer.json
Adds default devcontainer configuration from SSWG: https://github.com/swift-server/swift-devcontainer-template
Developing for linux can be challenging on macOS because some APIs are not available on Linux. By using VSCode and devcontainer you can essentially develop "on linux".
Adds devcontainer config.
When working in VSCode, you can now easily open the project inside a devcontainer.
=> Adds devcontainer config

.gitignore
`.devcontainer` should not be versioned to allow developers to customize it without git to interfere
=> Update .gitignore to ignore .devcontainer

.github/workflows/pull_request.yml, .gitignore, Package.swift, Package@swift-5.10.swift, Package@swift-5.swift, Tests/AWSLambdaEventsTests/ALBTests.swift, Tests/AWSLambdaEventsTests/APIGateway+EncodableTests.swift, Tests/AWSLambdaEventsTests/APIGateway+V2IAMTests.swift, Tests/AWSLambdaEventsTests/APIGateway+V2Tests.swift, Tests/AWSLambdaEventsTests/APIGatewayLambdaAuthorizerTest.swift, Tests/AWSLambdaEventsTests/APIGatewayTests.swift, Tests/AWSLambdaEventsTests/AppSyncTests.swift, Tests/AWSLambdaEventsTests/BedrockAgentTests.swift, Tests/AWSLambdaEventsTests/CloudFormationTests.swift, Tests/AWSLambdaEventsTests/CloudwatchTests.swift, Tests/AWSLambdaEventsTests/CognitoTests.swift, Tests/AWSLambdaEventsTests/DynamoDBTests.swift, Tests/AWSLambdaEventsTests/FunctionURLTests.swift, Tests/AWSLambdaEventsTests/LambdaGatewayProxyEventTests.swift, Tests/AWSLambdaEventsTests/S3Tests.swift, Tests/AWSLambdaEventsTests/SESTests.swift, Tests/AWSLambdaEventsTests/SNSTests.swift, Tests/AWSLambdaEventsTests/SQSTests.swift, Tests/AWSLambdaEventsTests/Utils/Base64Tests.swift, Tests/AWSLambdaEventsTests/Utils/DateWrapperTests.swift, Tests/AWSLambdaEventsTests/Utils/HTTPHeadersTests.swift, Tests/AWSLambdaEventsTests/Utils/IteratorTests.swift, Tests/AWSLambdaEventsTests/Utils/RFC5322DateParseStrategyTests.swift, scripts/format.sh
Migrate all unti tests to Swift Testing
Allows to compile and run test on open source Swift toolchain 6
Migrate according to 
https://developer.apple.com/documentation/testing/migratingfromxctest
```
􁁛  Test run with 101 tests passed after 0.012 seconds.
```
=> [test] Migrate unit tests to Swift Testing

Sources/AWSLambdaEvents/FunctionURL.swift
Add an `init()` to `FunctionURLResponse` to match the signature of `APIGatewayv2Response`
`APIGAtewayV2Response` and `FunctionURLResponse` share teh same structure, although we provided two different signatures for the initializers. This prevent writing common code to handle both responses.
- add a new `init(0` that has the same signature as the init from APIGatewayV2response
- make the current init as deprecated, we will remove it in a future version bump
Two init() functions on FunctionURLResponse
=> Add an init() that match the APIGatewayResponse

Sources/AWSLambdaEvents/FunctionURL.swift
In a previous PR (#91), a new init with a different parameters order was added, marking the previous one was deprecated. The problem is that the compiler doesn't know which one to choose when omitting the final parameters.
This PR fixes it by marking the deprecated init with `@_disfavoredOverload`.
=> Mark deprecated FunctionURLResponse init as @_disfavoredOverload

readme.md
Updated links in the getting started section to point to the latest tutorial and guide.
=> Update getting started links in readme
